# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-08 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordemservico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Criada'), (2, 'Delegada'), (3, 'Finalizada')], default=1),
        ),
    ]
