# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordemservico', '0002_auto_20180308_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Aberta'), (2, 'Aceita'), (3, 'Recusada')], default=1),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.Empresas'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='advogado',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='advogados.Advogados'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='ordemservico.OrdemServico'),
        ),
    ]
